In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv(r'C:\Users\alanm\Desktop\Dados\Python\dadosBrutos.csv')

In [ ]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

#### verificando quantas vezes o null aparece

In [54]:
df.isnull().sum()

work_year             10
experience_level       0
employment_type        0
job_title              0
salary                 0
salary_currency        0
salary_in_usd          0
employee_residence     0
remote_ratio           0
company_location       0
company_size           0
dtype: int64

### removendos os null

In [62]:
df[df.isnull().any(axis=1)]

,ano,nivel,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
5588,NaN,senior,FT,Product Manager,184500,USD,184500,US,0,US,M
59692,NaN,pleno,FT,Engineer,110000,USD,110000,DE,0,DE,M
59710,NaN,junior,FT,Data Scientist,208800,USD,208800,US,0,US,M
59759,NaN,senior,FT,Software Engineer,135000,USD,135000,US,0,US,M
59789,NaN,senior,FT,Engineer,112000,USD,112000,US,0,US,M
131000,NaN,senior,FT,Machine Learning Engineer,163800,USD,163800,US,0,US,M
131006,NaN,senior,FT,Data Analytics Manager,204500,USD,204500,US,0,US,M
133054,NaN,junior,FT,Data Scientist,40000,USD,40000,JP,100,MY,L
133281,NaN,pleno,FT,Machine Learning Engineer,180000,PLN,46597,PL,100,PL,L
133317,NaN,pleno,FT,Data Scientist,130000,USD,130000,US,50,US,L

In [65]:
df = df.dropna()

#### consultar as categorias das colunas

In [56]:
df['experience_level'].value_counts()

experience_level
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

#### Alterando nome das colunas

In [59]:
colunas = {
    'work_year' : 'ano',
     'experience_level' : 'nivel'   
   
}

df.rename(columns = colunas, inplace=True)

df.head()

,ano,nivel,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

#### Alterando nome dos Conteudos da colunas

In [61]:
nome_conteudo = {
    'SE' : 'senior',
    'MI' : 'pleno',
    'EN' : 'junior',
    'EX' : 'excecutivo'
}

df['nivel'] = df['nivel'].replace(nome_conteudo)

df['nivel'].value_counts()

nivel
senior        77241
pleno         40465
junior        12443
excecutivo     3200
Name: count, dtype: int64

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ano                 133339 non-null  float64
 1   nivel               133339 non-null  object
 2   employment_type     133339 non-null  object
 3   job_title           133339 non-null  object
 4   salary              133339 non-null  int64
 5   salary_currency     133339 non-null  object
 6   salary_in_usd       133339 non-null  int64
 7   employee_residence  133339 non-null  object
 8   remote_ratio        133339 non-null  int64
 9   company_location    133339 non-null  object
 10  company_size        133339 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 12.2+ MB

In [72]:
df = df.assign(ano = df['ano'].astype('int64'))

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ano                 133339 non-null  int64
 1   nivel               133339 non-null  object
 2   employment_type     133339 non-null  object
 3   job_title           133339 non-null  object
 4   salary              133339 non-null  int64
 5   salary_currency     133339 non-null  object
 6   salary_in_usd       133339 non-null  int64
 7   employee_residence  133339 non-null  object
 8   remote_ratio        133339 non-null  int64
 9   company_location    133339 non-null  object
 10  company_size        133339 non-null  object
dtypes: int64(4), object(7)
memory usage: 12.2+ MB

In [ ]:
df.to_csv(r'C:\Users\alanm\Desktop\Dados\Python\dadosLimpos.csv', index=False)